// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeslkzmqox_0-ttYViovKYI3Phlb8gZQ',
    appId: '1:98631669249:ios:1d6ec986f1aeb2c68d9200',
    messagingSenderId: '98631669249',
    projectId: 'favcoins-c2c60',
    storageBucket: 'favcoins-c2c60.appspot.com',
    iosBundleId: 'com.fav.coins',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIu7eNofloT0Fk1KNtZqg5dIf-sIsUMrs',
    appId: '1:98631669249:android:7dd2772b8d31b2818d9200',
    messagingSenderId: '98631669249',
    projectId: 'favcoins-c2c60',
    storageBucket: 'favcoins-c2c60.appspot.com',
  );

}